# Copy this folder and rename it to your item
# Then fill in the fields below.

title = ""
school = ""
curriculum = ""
subject = ""
# use an array for multiple grade levels
grade = []
# category: project | activity | presentation | cheat-sheet | tool | github-link
item_type = ""
checked = false

# Resources attached to this item
[[resources]]
type = "python"
path = "AST.py"
label = "full AST example"
[[resources]]
type = "python"
path = "code_generator.py"
label = "full code generator example"
[[resources]]
type = "python"
path = "compiler.py"
label = "full entry point example"
[[resources]]
type = "python"
path = "lexer.py"
label = "full lexer example"
[[resources]]
type = "python"
path = "parser.py"
label = "full parser example"
[[resources]]
type = "python"
path = "semantic_analyser.py"
label = "full semantic analyser example"
[[resources]]
type = "python"
path = "symbols.py"
label = "full symbol class definition example"
[[resources]]
type = "pdf"
path = "Compiler_project_instructions.py"
label = "instructions"
[[resources]]
type = "text"
path = "example.py"
label = "CIE pseudocode example"
