# Copy this folder and rename it to your item
# Then fill in the fields below.

title = "AI Lesson"
school = "MIST"
curriculum = "CIE"
subject = "Computer Science"
# use an array for multiple grade levels
grade = ["A2"]
# category: project | activity | presentation | cheat-sheet | tool | github-link
item_type = "presentation"
checked = false

# Resources attached to this item
[[resources]]
type = "pdf"
path = "A2_AI.pdf"
label = "presentation"
