# Copy this folder and rename it to your item
# Then fill in the fields below.

title = "Programming practice"
school = "MIST"
curriculum = "CIE"
subject = "Computer Science"
# use an array for multiple grade levels
grade = ["IGCSE"]
# category: project | activity | presentation | cheat-sheet | tool | github-link
item_type = "project"
checked = false

[[external_links]]
credits = "This project uses the fantastic Digital Logic Sim by Sebastian Lague"
label = "Used software"
url = "https://sebastian.itch.io/digital-logic-sim"

# Resources attached to this item
[[resources]]
type = "pdf"
path = "lets_make_a_CPU.pdf"
label = "instructions"
