# Copy this folder and rename it to your item
# Then fill in the fields below.

title = "Programming practice"
school = "MIST"
curriculum = "CIE"
subject = "Computer Science"
# use an array for multiple grade levels
grade = ["AS"]
# category: project | activity | presentation | cheat-sheet | tool | github-link
item_type = "activity"
checked = false

# Resources attached to this item
[[resources]]
type = "pdf"
path = "program_design_presentation.pdf"
label = "presentation and instructions"